### PR TITLE
Refactor/remove hardcoded data

### PR DESCRIPTION
**Pull request by mbenfowler**
## Description
This pr:
- Connect our clicked recipes to their fetched ingredient data rather than initial hardcoded data
- delete all initial data files to ensure reliance on our fetched data
- remove outdated import/export references
- move `getRecipeCard` out of `scripts` and over to our `apiCalls` where other data is maintained
- remove unneeded initial hardcoded HTML

## Testing Notes
- test entire user flows, no visible changes should be introduced

### CODE REVIEW

**Comment by mbenfowler** [comment]
[Ensure data model and dom are separated. functions that’ll alter data model should not be kept in domUpdates file.](https://trello.com/c/Lch8Mj5z/44-ensure-data-model-and-dom-are-separated-functions-thatll-alter-data-model-should-not-be-kept-in-domupdates-file)

**Comment by mbenfowler** [comment]
[Remove hardcoded ingredients data](https://trello.com/c/km9suPmm/43-remove-hardcoded-ingredients-data)

**Review by lauraguerra1 — APPROVED** [review]
This looks good to me!

**Review by taranveersingh93 — APPROVED** [review]
Looks good

**Pull request merged**
