### PR TITLE
Refactor/audit dm dom separation and search clearing

### PR DESCRIPTION
**Pull request by lauraguerra1**
Description

- allow search clear/reset 
- change active tag color
- separate data manipulation from domUpdates and add tests 

Testing Notes

- 52 tests passing 
- As a user, one should be able to press enter to search for recipes 
- As a user, one should be able to press the search clear button to clear the search bar and re-render the recipes of interest 

Extra Notes 
- As an extra test, please try searching for an item, clearing the search and searching for a new item. 
- Please also try an invalid search, clearing the search and searching for another new item

### CODE REVIEW

**Review by taranveersingh93 — APPROVED** [review]
Super awesome

**Review by mbenfowler — CHANGES_REQUESTED** [review]
Looks like this introduced a bug!  When you have a filter selected and then attempt to add one of the filtered recipes to your recipesToCook, it does add it but it kicks you back to the full list of recipes and the filter is still highlighted.  At a glance I'm unable to tell where this could be happening, but maybe somewhere around your new `renderRecipesOfInterest` function?  Lemme know if you wanna jump on zoom to troubleshoot.

**Comment by taranveersingh93** [comment]
Looks good now. The bug got fixed

**Review by mbenfowler — APPROVED** [review]
Amazing.

**Comment by mbenfowler** [comment]
[Ensure data model and dom are separated. functions that’ll alter data model should not be kept in domUpdates file.](https://trello.com/c/Lch8Mj5z/44-ensure-data-model-and-dom-are-separated-functions-thatll-alter-data-model-should-not-be-kept-in-domupdates-file)

**Pull request merged**
